import { Command } from "../types";

export const COMMANDS_LIST: Command[] = [
    {
        id: 15,
        name: "Ping",
        description: "Check a node presence",
        targetType: "node",
        parameters: [],
        responseType: "ACK",
    },
    {
        id: 20,
        name: "Get restart count",
        description: "Get the number of restarts of the node",
        targetType: "node",
        parameters: [],
        responseType: "int",
    },
    {
        id: 25,
        name: "Set restart count",
        description: "Set the number of restarts of the node",
        targetType: "node",
        parameters: [
            {
                id: 1,
                name: "Restart count",
                type: "int",
                default: 0,
                minValue: 0,
                maxValue: 100_000,
            },
        ],
        responseType: "ACK",
    },
    {
        id: 30,
        name: "Read",
        description: "Read the nodes wattmeter",
        targetType: "node",
        parameters: [],
        responseType: "float",
    },
    {
        id: 35,
        name: "Sanity check",
        description: "Check the nodes sanity",
        targetType: "node",
        parameters: [],
        responseType: "bool",
    },
    {
        id: 40,
        name: "Get non-response count",
        description: "Get the number of non-responses of the coordinator nodes",
        targetType: "coordinator",
        parameters: [],
        responseType: "int",
    },
    {
        id: 45,
        name: "Get sampling time",
        description: "Get the sampling time of the coordinator (in seconds)",
        targetType: "coordinator",
        parameters: [],
        responseType: "int",
    },
    {
        id: 50,
        name: "Set sampling time",
        description: "Set the sampling time of the coordinator (in seconds)",
        targetType: "coordinator",
        parameters: [
            {
                id: 1,
                name: "Sampling time",
                type: "int",
                default: 60,
                minValue: 60,
                maxValue: 3600,
            },
        ],
        responseType: "ACK",
    },
    {
        id: 55,
        name: "Pause sampling",
        description: "Pause the sampling of the coordinator",
        targetType: "coordinator",
        parameters: [],
        responseType: "ACK",
    },
    {
        id: 60,
        name: "Resume sampling",
        description: "Resume the sampling of the coordinator",
        targetType: "coordinator",
        parameters: [],
        responseType: "ACK",
    },
    {
        id: 65,
        name: "Get sampling state",
        description: "Get the sampling state of the coordinator",
        targetType: "coordinator",
        parameters: [],
        responseType: "bool",
    },
];